name: Deploy Prod
# Run this workflow every time a new commit pushed to your repository
on: push

jobs:

  deploy-prod:

    name: java.no

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: yarn ci
    - name: build
      run: yarn build
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v2.9.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: build